// <auto-generated />
using System;
using AspnetCoreStarter.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspnetCoreStarter.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250727144531_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspnetCoreStarter.Models.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Adres")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Telefon")
                        .IsUnique();

                    b.ToTable("Musteriler", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdSoyad = "Ahmet Yılmaz",
                            Adres = "İstanbul, Kadıköy",
                            Aktif = true,
                            CreateDate = new DateTime(2025, 7, 27, 17, 45, 30, 274, DateTimeKind.Local).AddTicks(7184),
                            Email = "ahmet.yilmaz@email.com",
                            Telefon = "0532-123-4567"
                        },
                        new
                        {
                            Id = 2,
                            AdSoyad = "Ayşe Kaya",
                            Adres = "Ankara, Çankaya",
                            Aktif = true,
                            CreateDate = new DateTime(2025, 7, 27, 17, 45, 30, 274, DateTimeKind.Local).AddTicks(7457),
                            Email = "ayse.kaya@email.com",
                            Telefon = "0533-987-6543"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
